### ISSUE TITLE
POSIX Warning on compliant secret 

### ISSUE THREAD

**Issue by rvoitenko** [abhilash1in/aws-secrets-manager-action#20]
Hello,

I always get warnings about secrets names not POSIX compliant.
To verify it I've created secret "TEST" with key "KEY" and value "VALUE", so it's json looks like:
```
{
  "KEY": "VALUE"
}
```

and the step looks like this:
```
    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v1.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        secrets: TEST
        parse-json: true
```

In debug mode I see the following:
```
##[debug]Secret name 'TEST.KEY' is not POSIX compliant. It will be transformed to 'TEST_KEY'.
##[debug]Injecting environment variable 'TEST_KEY'.
##[debug]Node Action run completed with exit code 0
##[debug]TEST_KEY='***'
##[debug]Finishing: Read secrets from AWS Secrets Manager into environment variables
```

Which means that 'TEST.KEY' is analyzed as secret name, but it not secret name. It's concatenated secret name + '.' + secret key.
Is this is a bug?

**Comment by abhilash1in** [comment]
You probably have `parse-json` set to true. Due to this, the new secret name becomes `TEST.KEY` which is then transformed into `TEST_KEY` to make it compliant. 

If you set `parse-json` to false, the secret name will remain `TEST`. Note that the secret value will be your raw JSON string in this case.

**Comment by rvoitenko** [comment]
Thank you for explanation.
But that's mean that with "parse-json=true" you always get this warning.
Maybe change logic and make exception, when JSON flattening happen do analyze separately left part and right part of *{Original AWS Secret Key}.{JSON Key}* ?

**Comment by abhilash1in** [comment]
That makes sense. I'll look into it. Thank you for the suggestion! For now, you can safely ignore the warning.

Feel free to submit a PR if you want to make the change yourself :)

**Comment by rvoitenko** [comment]
Ok, thanks for suggestion. I can ignore warnings, but it's annoying, because when I have secret with 5 key/values inside I get 5 warnings :) even I need only one key.
I will try to submit PR after my local testing.

**Comment by emmanuelnk** [comment]
Hi, I'm still getting this error even with the latest commit. I think this issue should be re-opened.

As you can see from the screenshot, I'm using the latest commit.

![image](https://user-images.githubusercontent.com/19330930/130230660-00885c47-994b-4c37-872a-717effe1717b.png)
