### ISSUE TITLE
Noisy POSIX warning

### ISSUE THREAD

**Issue by oschlegel** [abhilash1in/aws-secrets-manager-action#32]
Hi, i'm getting a lot of warnings from your action like "One of the secrets has a name that is not POSIX compliant...", because basically all my secrets are not POSIX compliant. But since the conversion behavior is already documented in the readme and works fine i think it would be ok to use a debug message instead of a warning, this way it can still help to analyze and track down issues but doesn't clutter the workflow logs.

**Comment by jbabala-costa** [comment]
Hi, I have exactly same issue. Could we introduce flag to suppress such warnings?

**Comment by abhilash1in** [comment]
Will be fixed with release 2.1.0 (coming soon, today or tomorrow).

**Comment by sharat87** [comment]
Hey, looks like this warning is still there. Can you confirm if I'm doing something wrong here please?

![Screenshot 2022-06-15 at 14 23 15](https://user-images.githubusercontent.com/120119/173786143-e78c52f6-3595-467f-a4ec-699201b33d65.png)

The variables do actually load and work fine though.

Thank you for your work.

**Comment by abhilash1in** [comment]
@sharat87 you need to set `disable-warnings: true` in order to disable and suppress POSIX warnings.

**Comment by sharat87** [comment]
Hey @abhilash1in, thanks for sharing that. But wouldn't that hide _all_ POSIX warnings? Is it possible to just hide this one particular warning?
